id: P006935
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13781
  title: རྡུལ་ཚོན་དང་སྐུ་གདུང་ཐིག་རྩ་གཟུངས་གཞུག་བཅས་ཀྱི་ལག་ལེན།
  author: ''
  volumes:
    639ce25e1c0441a696cd175f1d32a360:
      image_group_id: I1KG15281
      title: ''
      volume_number: 1
      total_pages: 112
ebook_metadata:
  title: རྡུལ་ཚོན་དང་སྐུ་གདུང་ཐིག་རྩ་གཟུངས་གཞུག་བཅས་ཀྱི་ལག་ལེན།
  author: ''
  sku: P006935
  cover: cover.jpg
  layers:
  - pagination
