id: P006935
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:38.075878
source_metadata:
  id: bdr:W1KG13781
  title: རྡུལ་ཚོན་དང་སྐུ་གདུང་ཐིག་རྩ་གཟུངས་གཞུག་བཅས་ཀྱི་ལག་ལེན།
  author: ''
  volumes:
    73f52f6356234e7cba3e8eeffc54659c:
      image_group_id: I1KG15281
      title: Volume 1 of rdul tshon dang sku gdung thig rtsa gzungs gzhug bcas kyi
        lag len/
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
