id: IB6E5BEE5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:59:49+00:00'
last_modified: '2022-06-08T12:40:17.074827+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13781
  title: རྡུལ་ཚོན་དང་སྐུ་གདུང་ཐིག་རྩ་གཟུངས་གཞུག་བཅས་ཀྱི་ལག་ལེན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C955:
      image_group_id: I1KG15281
      title: Volume 1 of rdul tshon dang sku gdung thig rtsa gzungs gzhug bcas kyi
        lag len/
      total_pages: 112
      order: 1
      base_file: C955.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
